// Hình pixel art cho trang CV, viết dạng lưới ký tự: mỗi ký tự là một điểm ảnh, "." là trong suốt.
// Màu lấy theo bảng `pal`. pixel.js đọc các hình này và vẽ ra canvas.
window.PX = {
  pal: {
    k: '#04070e', // viền
    w: '#f8fafc', l: '#cbd5e1', g: '#94a3b8', d: '#475569', s: '#273552',
    c: '#22d3ee', C: '#a5f3fc', b: '#0e7490',
    i: '#6366f1', I: '#a5b4fc', p: '#a855f7', P: '#d8b4fe',
    e: '#34d399', y: '#facc15', Y: '#fef08a', o: '#f59e0b', O: '#b45309',
    r: '#f43f5e', m: '#9f1239',
    u: '#f1c27d', U: '#d29a63', h: '#5a3a28', H: '#8b5e3c',
    B: '#3b82f6', N: '#3730a3', q: '#f19a8e',
  },

  // Biểu tượng 12x12, khóa trùng tên biểu tượng SVG (#i-db -> db)
  icons: {
    db: [
      '..kkkkkkkk..',
      '.kCCCCCCCCk.',
      'kCwCCCCCCCCk',
      'kbCCCCCCCCbk',
      'kcbbbbbbbbck',
      'kccccccceeck',
      'kbccccccccbk',
      'kcbbbbbbbbck',
      'kccccccceeck',
      'kbccccccccbk',
      '.kbbbbbbbbk.',
      '..kkkkkkkk..',
    ],
    chip: [
      '...l.l.l....',
      '...g.g.g....',
      '..kkkkkkk...',
      'lgkwsssskgl.',
      '..ksbbbsk...',
      'lgksbcbskgl.',
      '..ksbbbsk...',
      'lgkssssskgl.',
      '..kkkkkkk...',
      '...g.g.g....',
      '...l.l.l....',
      '............',
    ],
    layers: [
      '.....kk.....',
      '...kkCCkk...',
      '.kkCCwCCCkk.',
      'kcCCCCCCCCck',
      '.kkcCCCCckk.',
      'kiikkCCkkiik',
      '.kkiikkiikk.',
      'kppkkiikkppk',
      '.kkppkkppkk.',
      '...kkppkk...',
      '.....kk.....',
      '............',
    ],
    chart: [
      '.dddddddddd.',
      'dssssssssssd',
      'dsssssssPPsd',
      'dsssssssppsd',
      'dssssIIsppsd',
      'dssssiisppsd',
      'dsCCsiisppsd',
      'dsccsiisppsd',
      'dddddddddddd',
      '....kddk....',
      '...kkddkk...',
      '..kddddddk..',
    ],
    plug: [
      '....l..l....',
      '....l..l....',
      '..kkkkkkkk..',
      '..kIiiiiik..',
      '..kIiieiik..',
      '..kiiiiiik..',
      '...kiiiik...',
      '....kkkk....',
      '.....cc.....',
      '.....cc.....',
      '.....cccccCC',
      '............',
    ],
    flask: [
      '...kkkkkk...',
      '....kllk....',
      '....kClk....',
      '....kllk....',
      '...kllllk...',
      '..kllllllk..',
      '.kcCcccccck.',
      '.kcccccwcck.',
      'kccwccccccck',
      'kbccccccccbk',
      '.kkkkkkkkkk.',
      '............',
    ],
    code: [
      'dddddddddddd',
      'dryedddddddd',
      'dddddddddddd',
      'dssssssssssd',
      'dscsIIIIIssd',
      'dsscsssssssd',
      'dscsPPPssssd',
      'dssssssssssd',
      'dssswwsssssd',
      'dssssssssssd',
      'dddddddddddd',
      '............',
    ],
    cap: [
      '............',
      '.....kk.....',
      '...kkIIkk...',
      '.kkIIIiiikk.',
      'kiiiiiiiiiik',
      '.kkiiiiiikky',
      '..kddddddk.y',
      '..kddddddk.y',
      '..kddddddk.Y',
      '...kkkkkk...',
      '............',
      '............',
    ],
    gear: [
      '....kkkk....',
      '.kk.kllk.kk.',
      '.klkkglkkgk.',
      '..kggggggk..',
      'kkkggkkggkkk',
      'klggk..kgggk',
      'kgggk..kgggk',
      'kkkggkkggkkk',
      '..kggggggk..',
      '.kgkkggkkgk.',
      '.kk.kggk.kk.',
      '....kkkk....',
    ],
    globe: [
      '...kkkkkk...',
      '.kkCcceeckk.',
      '.kCcecceeck.',
      'kCceeccceeck',
      'kcceeeccceck',
      'kccceeccccck',
      'kccccecceeck',
      'kbcccccceebk',
      'kbbcceeccbbk',
      '.kbbceebbbk.',
      '.kkbbbbbbkk.',
      '...kkkkkk...',
    ],
    mail: [
      '............',
      '..........rr',
      'kkkkkkkkkkrr',
      'kgwwwwwwwwgk',
      'klgwwwwwwglk',
      'kllgwwwwgllk',
      'klllgwwglllk',
      'kllllggllllk',
      'kllllllllllk',
      'kllllllllllk',
      'kkkkkkkkkkkk',
      '............',
    ],
    phone: [
      '..dddddddd..',
      '..dddggddd..',
      '..dssssssd..',
      '..dswwwssd..',
      '..dssssssd..',
      '..dsscccsd..',
      '..dssssssd..',
      '..dswwsssd..',
      '..dssssssd..',
      '..dddddddd..',
      '..dddggddd..',
      '............',
    ],
    pin: [
      '...kkkkkk...',
      '..krrrrrrk..',
      '.krwwrrrrrk.',
      '.krwrkkrrrk.',
      '.krrkwwkrrk.',
      '.krrkwwkrrk.',
      '.krrrkkrrrk.',
      '..krrrrrrk..',
      '...krrrrk...',
      '....krrk....',
      '.....kk.....',
      '...ssssss...',
    ],
    brief: [
      '............',
      '....kkkk....',
      '...khkkhk...',
      '.kkkkkkkkkk.',
      'kHHHHHHHHHHk',
      'kHwHHHHHHHHk',
      'khhhhyyhhhhk',
      'kHHHHyyHHHHk',
      'kHHHHHHHHHHk',
      'kHHHHHHHHHhk',
      '.kkkkkkkkkk.',
      '............',
    ],
    cal: [
      '..g.....g...',
      '.kgkkkkkgkk.',
      '.krrrrrrrrk.',
      '.krrrrrrrrk.',
      '.kwwwwwwwwk.',
      '.kwdwdwdwwk.',
      '.kwwwwwwwwk.',
      '.kwdwcwdwwk.',
      '.kwwwwwwwwk.',
      '.kwdwdwwwwk.',
      '.kkkkkkkkkk.',
      '............',
    ],
    py: [
      '..kkkkkk....',
      '.kBBBBBBk...',
      '.kBwBBBBk...',
      '.kkkkBBBk...',
      'kBBBBBBBkkk.',
      'kBBBBBBkyyyk',
      'kBBBkyyyyyyk',
      '.kkkyyyyyyyk',
      '...kyyyykkk.',
      '...kyyyywyk.',
      '...kyyyyyyk.',
      '....kkkkkk..',
    ],
    js: [
      'kkkkkkkkkkkk',
      'kYyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyykykkkyk',
      'kyyyykykyyyk',
      'kyyyykykkkyk',
      'kyykykyyykyk',
      'kyykkkykkkyk',
      'kyyyyyyyyyyk',
      'kkkkkkkkkkkk',
    ],
    cs: [
      '..kkkkkkkk..',
      '.kPPPPPPPPk.',
      'kppppppppppk',
      'kpwwwppwpwpk',
      'kpwpppwwwwwk',
      'kpwppppwpwpk',
      'kpwpppwwwwwk',
      'kpwwwppwpwpk',
      'kppppppppppk',
      'kiiiiiiiiiik',
      '.kiiiiiiiik.',
      '..kkkkkkkk..',
    ],
    eye: [
      'cc........cc',
      'c..........c',
      '....kkkk....',
      '..kkllllkk..',
      '.kllkkkkllk.',
      'kllkcwcckllk',
      'kllkckkckllk',
      '.kllkkkkllk.',
      '..kkllllkk..',
      '....kkkk....',
      'c..........c',
      'cc........cc',
    ],
  },

  // Nhân vật (quay phải) cầm laptop, 10x16: đứng và bước chân
  hero: {
    stand: [
      '...hhhh...',
      '..hhhhhhh.',
      '.hhhHhhhhh',
      '.hhhuuuuu.',
      '.hhuuukuu.',
      '..huuuuuu.',
      '...uuuU...',
      '..iiiiii..',
      '.iiIiiidd.',
      '.iiIiiidc.',
      '.iiiiuuddd',
      '..iiiiii..',
      '..ssssss..',
      '..ss..ss..',
      '..ss..ss..',
      '..kk..kk..',
    ],
    legs: [
      '..ssssss..',
      '.ss....ss.',
      '.ss....ss.',
      'kk.....kk.',
    ],
  },

  // Bong bóng "!" trên đầu nhân vật
  bubble: [
    '.kkkkk.',
    'kwwowwk',
    'kwwowwk',
    'kwwowwk',
    'kwwwwwk',
    'kwwowwk',
    '.kkkkk.',
    '..k....',
  ],

  // Chân dung trong hộp thoại, 16x16. faceBlink / faceTalk thay một số dòng.
  face: [
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hHHhhhhhhh...',
    '...hhhuhhuhhh...',
    '...huuuuuuuuh...',
    '...hukuuuukuh...',
    '...hukuuuukuh...',
    '...huuuuuuuuh...',
    '....uuukkuuu....',
    '.....uuuuuu.....',
    '...iiiuuuuiii...',
    '..iiiiiuuiiiii..',
    '.iIiiiiiiiiiiIi.',
    '.iIiiiiiiicciIi.',
  ],
  faceBlink: {
    7: '...huuuuuuuuh...',
    8: '...hkkuuuukkh...',
  },
  faceTalk: {
    10: '....uuukkuuu....',
    11: '.....uummuu.....',
  },

  // Cây thông (a: tán, b: phía được trăng chiếu, n: thân)
  pine: [
    '...a...',
    '..aab..',
    '..aab..',
    '.aaabb.',
    '..aab..',
    '.aaabb.',
    'aaaabbb',
    '.aaabb.',
    'aaaaabb',
    'aaaabbb',
    '...n...',
    '...n...',
  ],
  pineBig: [
    '....a....',
    '...aab...',
    '...aab...',
    '..aaabb..',
    '...aab...',
    '..aaabb..',
    '.aaaabbb.',
    '..aaabb..',
    '.aaaabbb.',
    'aaaaabbbb',
    '.aaaabbb.',
    'aaaaaabbb',
    'aaaaabbbb',
    '....n....',
    '....n....',
    '....n....',
  ],

  // Mèo cam ở chân trang (quay phải), 2 khung chạy
  cat: {
    a: [
      '........O..O',
      'O.......oooo',
      'O.......ooko',
      '.Ooooooooooo',
      '..oOoOoooww.',
      '..ooooooww..',
      '..o.o...o.o.',
      '..O.O...O.O.',
    ],
    b: [
      '........O..O',
      'O.......oooo',
      'O.......ooko',
      '.Ooooooooooo',
      '..oOoOoooww.',
      '..ooooooww..',
      '.o..o..o..o.',
      '.O..O..O..O.',
    ],
  },

  // Chữ pixel 3x5 cho nhãn trên tháp máy chủ
  font: {
    S: ['###', '#..', '###', '..#', '###'],
    Q: ['###', '#.#', '#.#', '##.', '..#'],
    L: ['#..', '#..', '#..', '#..', '###'],
  },
};

// PostgreSQL dùng lại hình cơ sở dữ liệu, đổi sang tông chàm
window.PX.icons.pg = window.PX.icons.db.map(r => r.replace(/c/g, 'i').replace(/C/g, 'I').replace(/b/g, 'N'));

// Hình lớn gom từ các khối vuông (pixel.js > mosaic): chân dung 32x32, huy hiệu 24x24
window.PX.art = {
    // Chân dung: tóc nâu, kính, áo hoodie có logo </>
    portrait: [
      '................................',
      '................................',
      '............kkkkkkkk............',
      '..........kkhhhhhhhhkk..........',
      '.........khHHHhhhhhhhhk.........',
      '........khHHhhhhhhHHhhhk........',
      '.......khHHhhhhhhhhhHhhhk.......',
      '.......khHhhhhhhhhhhhHhhk.......',
      '.......khhhhhhhhhhhhhhhhk.......',
      '......khhhhhHhhhhHhhhhhhhk......',
      '......khhhhhhHhhhhHhhHhhhk......',
      '......khhhhhhhhhhhhhhhhhhk......',
      '......khhhhuhhuuuuuuuUUkhk......',
      '......khuukkkkkuukkkkkUUhk......',
      '......khuukCkukkkkCkukUUuk......',
      '......kuUukukukuukukukUUuk......',
      '......kuuukkkkkuukkkkkUUuk......',
      '.......kuuuuuuuuUuuuuUUUk.......',
      '........kkuqukuuuuukUqkk........',
      '..........kuuukmmmkuUk..........',
      '.........kkkuuuuuuuukkk.........',
      '........kIIIIuuuuuuIIIIk........',
      '........kIIIIUUUUUUIIIIk........',
      '......kkiIIIIuuuuuuIIIIikk......',
      '....kkIiiIIIIwiiiiwIIIIiNNkk....',
      '...kIIIiiiiiiwiiiiwiiiiiNNNNk...',
      '..kIIIIiiiiiiwiiiiwiiciiccNNNk..',
      '..kIIIIiiiiiiwiiiiwiciicNNcNNk..',
      '..kiiiiiiiiiiliiiiliicciNcNNNk..',
      '..kiiiiiiiiiiiiiiiiiiiiiNNNNNk..',
      '..kiiiiiiiiiiiiiiiiiiiiiNNNNNk..',
      '..kiiiiiiiiiiiiiiiiiiiiiNNNNNk..',
    ],
    // Huy chương tốt nghiệp loại Giỏi
    grad: [
      '....krrmmk....kiiNNk....',
      '....krrmmk....kiiNNk....',
      '.....krrmmk..kiiNNk.....',
      '.....krrmmk..kiiNNk.....',
      '......krrmmkkiiNNk......',
      '......krrmmkkiiNNk......',
      '.......krrmmiiNNk.......',
      '.......krrmooiNNk.......',
      '.......kooooooook.......',
      '......koowyyyyyook......',
      '.....koowyyyyyyyook.....',
      '....kooyyYYYYyyyyook....',
      '....koyyYYYYOyyyyyok....',
      '....koyyYYYyOyyyyyok....',
      '...kooyyYOOOOOOOyyook...',
      '...kooyyYyOOOOOyyyook...',
      '....koyyyyyOOOyyyyok....',
      '....koyyyyOOyOOyyyok....',
      '....kooyyyOyyyOyyook....',
      '.....kooyyyyyyyyook.....',
      '......kooyyyyyyook......',
      '.......kooooooook.......',
      '........kkkookkk........',
      '...........kk...........',
    ],
    // Chip AI: khóa học Samsung SIC
    ai: [
      '........................',
      '......kk.kk.kk.kk.......',
      '.....kllkllkllkllk......',
      '....kkggkggkggkggkkk....',
      '...kddddddddddddddddk...',
      '..kkdssssssssssssssdkk..',
      '.klgdsNNNNNNNNNNNNsdglk.',
      '.klgdsNIINNNNNNNNNsdglk.',
      '..kkdsNINNNNNNNNNNsdkk..',
      '.klgdsNNCCCNNCCCNNsdglk.',
      '.klgdsNNCNCNNNCNNNsdglk.',
      '..kkdsNNCCCNNNCNNNsdkk..',
      '.klgdsNNCNCNNNCNNNsdglk.',
      '.klgdsNNCNCNNCCCNNsdglk.',
      '..kkdsNNNNNNNNNNNNsdkk..',
      '.klgdsNNccccccccNNsdglk.',
      '.klgdsNNNNNNNNNPpNsdglk.',
      '..kkdsNNNNNNNNNNNNsdkk..',
      '...kdssssssssssssssdk...',
      '...kddddddddddddddddk...',
      '....kkggkggkggkggkkk....',
      '.....kllkllkllkllk......',
      '......kk.kk.kk.kk.......',
      '........................',
    ],
    // Sách: bài báo in trong sách của Springer
    book: [
      '........................',
      '.................k......',
      '.....kkkkkkkkkkkkYk.....',
      '....kNNNiiiiiiiiYYYk....',
      '....kNNNiiiiiiiiiYwwk...',
      '....kNNNiiiiiiiiiiwlk...',
      '....kNNNiIIIIIIIIiwwk...',
      '....kNNNiICCCCCCIiwlk...',
      '....kNNNiICCCCIIIiwwk...',
      '....kNNNiIIIIIIIIiwlk...',
      '....kNNNiiiiiiiiiiwwk...',
      '....kNNNiiiiiiiiiiwlk...',
      '....kNNNiIIIIIIIIiwwk...',
      '....kNNNiiiiiiiiiiwlk...',
      '....kNNNiIIIIIIIIiwwk...',
      '....kNNNiiiiiiiiiiwlk...',
      '....kNNNiIIIIIiiiiwwk...',
      '....kNNNiiiiiiiiiiwlk...',
      '....kNNNiiiiiiiiiiwwk...',
      '....kNNNiiiiiirriiwlk...',
      '.....kwwwwwwwwrrwwwwk...',
      '.....kllllllllrrllllk...',
      '......kkkkkkkkrmkkkk....',
      '..............krk.......',
    ],
};
